# Generated by Django 6.0.6 on 2026-06-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='ville',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='boutiques', to='core.city', verbose_name='Ville'),
            preserve_default=False,
        ),
    ]
