# Generated by Django 6.0.6 on 2026-06-26 11:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Label')),
            ],
            options={
                'verbose_name': "Tag d'avis",
                'verbose_name_plural': "Tags d'avis",
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.TextField(blank=True, default='', max_length=500, verbose_name='Commentaire')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
                ('tags', models.ManyToManyField(blank=True, related_name='reviews', to='reviews.reviewtag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=300, verbose_name='Réponse')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.review', verbose_name='Avis')),
            ],
            options={
                'verbose_name': 'Réponse à un avis',
                'verbose_name_plural': 'Réponses aux avis',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('FAUX_AVIS', 'Faux avis'), ('DIFFAMATION', 'Diffamation'), ('CONTENU_INAPPROPRIE', 'Contenu inapproprié'), ('SPAM', 'Spam')], max_length=30, verbose_name='Raison')),
                ('comment', models.TextField(blank=True, default='', max_length=500, verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEE', 'Traitée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='Signaleur')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='Avis signalé')),
            ],
            options={
                'verbose_name': "Signalement d'avis",
                'verbose_name_plural': "Signalements d'avis",
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'review'), name='unique_report_per_review')],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'seller'), name='unique_review_per_seller'),
        ),
    ]
