# Generated by Django 6.0.6 on 2026-06-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('label_fr', models.CharField(max_length=255, verbose_name='Label (FR)')),
                ('attribute_type', models.CharField(choices=[('INT', 'Entier'), ('DECIMAL', 'Décimal'), ('CHOICE', 'Choix unique'), ('MULTI_CHOICE', 'Choix multiple'), ('BOOLEAN', 'Booléen'), ('TEXT_SHORT', 'Texte court')], max_length=20, verbose_name='Type')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('filterable', models.BooleanField(default=False, verbose_name='Filtrable')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur min')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur max')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
            ],
            options={
                'verbose_name': "Définition d'attribut",
                'verbose_name_plural': "Définitions d'attributs",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255, verbose_name='Valeur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.attributedefinition', verbose_name='Attribut')),
            ],
            options={
                'verbose_name': "Choix d'attribut",
                'verbose_name_plural': "Choix d'attributs",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attributedefinition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category', verbose_name='Catégorie'),
        ),
    ]
