# Generated by Django 6.0.6 on 2026-06-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='depends_on_choice',
            field=models.ForeignKey(blank=True, help_text="Si renseigné, cet attribut n'apparaît que quand ce choix est sélectionné", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_attributes', to='catalog.attributechoice', verbose_name='Dépend du choix'),
        ),
    ]
