# Generated by Django 6.0.6 on 2026-06-26 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description_complementaire', models.TextField(blank=True, default='', max_length=300, verbose_name='Description complémentaire')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DH)')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDU', 'Vendu'), ('ARCHIVE', 'Archivé')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('is_boosted', models.BooleanField(default=False, verbose_name='Boosté')),
                ('boost_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du boost')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('whatsapp_clicks_count', models.PositiveIntegerField(default=0, verbose_name='Clics WhatsApp')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Catégorie')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.city', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': "Image d'annonce",
                'verbose_name_plural': "Images d'annonce",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Valeur entière')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur décimale')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Valeur booléenne')),
                ('value_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Valeur texte')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attributedefinition', verbose_name='Attribut')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product', verbose_name='Annonce')),
                ('value_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_values', to='catalog.attributechoice', verbose_name='Valeur choix')),
                ('value_multi_choice', models.ManyToManyField(blank=True, related_name='multi_choice_values', to='catalog.attributechoice', verbose_name='Valeurs choix multiples')),
            ],
            options={
                'verbose_name': "Valeur d'attribut",
                'verbose_name_plural': "Valeurs d'attributs",
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
