# Generated by Django 6.0.6 on 2026-06-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWhatsAppClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_clicks', to='products.product', verbose_name='Annonce')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_clicks', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Clic WhatsApp',
                'verbose_name_plural': 'Clics WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.product', verbose_name='Annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Clé de session')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='products.product', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': 'Vue de produit',
                'verbose_name_plural': 'Vues de produits',
                'unique_together': {('product', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('FRAUDULEUSE', 'Annonce frauduleuse'), ('PRIX_IRREALISTE', 'Prix irréaliste'), ('PRODUIT_INTERDIT', 'Produit interdit'), ('CONTENU_INAPPROPRIE', 'Contenu inapproprié'), ('DOUBLON', 'Doublon')], max_length=30, verbose_name='Raison')),
                ('comment', models.TextField(blank=True, default='', max_length=500, verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEE', 'Traitée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product', verbose_name='Annonce')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Signaleur')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'unique_together': {('reporter', 'product')},
            },
        ),
    ]
