# Generated by Django 6.0.6 on 2026-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productwhatsappclick_favorite_productview_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('COMME_NEUF', 'Comme neuf'), ('TRES_BON', 'Très bon état'), ('BON', 'Bon état'), ('CORRECT', 'État correct')], default='BON', max_length=20, verbose_name='État'),
        ),
    ]
