# Generated by Django 6.0.6 on 2026-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_condition_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garantie',
            field=models.BooleanField(default=False, verbose_name='Garantie incluse'),
        ),
        migrations.AddField(
            model_name='product',
            name='livraison',
            field=models.BooleanField(default=False, verbose_name='Livraison disponible'),
        ),
    ]
